#!/usr/bin/env bash

set -euxo pipefail

export RESULTS_DIR="./results"
mkdir -p ${RESULTS_DIR}

echo $CONT
echo $DATADIR
echo $BACKBONE_DIR

srun \
    --mpi=none \
    --ntasks="$(( DGXNNODES * DGXNGPU ))" \
    --ntasks-per-node="${DGXNGPU}" \
    --container-image="${CONT}" \
    --container-workdir=/workspace/single_stage_detector/ssd \
    --container-mounts=${DATADIR}:/datasets/open-images-v6-mlperf,${BACKBONE_DIR}:/root/.cache/torch,${RESULTS_DIR}:/results \
    ./run_and_time.sh
